Environment concept docs
resource-watch/doc-api pull request #170
Opened 2020-12-18 13:17 UTC by tiagojsag

2020-12-21 10:43 UTC, ikas requested changes
Env text LGTM :ok_hand: I'd suggest reviewing the remaining docs searching for references to environment, remove any duplicate definitions of environment and point here instead :)

2020-12-21 11:55 UTC, ikas approved these changes
LGTM :ok_hand:

2020-12-22 16:51 UTC, ethanroday commented
I think it's worth adding some language clarifying that `production` the _only_ special value for `env` (i.e. the only one that actually changes behavior), and that the field is otherwise unrestricted and can be any string you want. Otherwise, looks good!

@ikas no need to send this back for review. Feel free to just add language similar to the above and then merge.

2020-12-22 16:51 UTC, ethanroday approved these changes

2020-12-22 17:35 UTC, merged