Initial version of the graph concept docs
resource-watch/doc-api pull request #175
Opened 2020-12-29 15:01 UTC by ikas

An initial version of the graph concept docs. Might require some tweaking after the graph endpoint docs.

Related to [GTC-729](https://gfw.atlassian.net/browse/GTC-729).

2020-12-30 11:40 UTC, tiagojsag requested changes

2020-12-30 11:40 UTC, tiagojsag commented on source/includes/concept/_graph.md
> +The RW API provides you different ways to search for the information you are looking for: from [searching datasets](/index-rw.html#search) by keyword and exploring [dataset metadata](/index-rw.html#m
remove the /index-rw.html from the links please

2020-12-30 17:53 UTC, ethanroday requested changes
All the graph stuff happens automatically under the hood, right? I would add some language that basically says, "this is stuff you get for free when you upload/tag a dataset and is mostly read-only". Otherwise looks good!

2021-01-04 11:25 UTC, ikas commented
Hey Ethan - users have to explicitly define the graph relationships for their datasets. Graph endpoint docs were severely incomplete and most creation/edition/deletion endpoints were not documented. So, the answer to your question is no, this is not at all automatic - we'll explain how users can do it in the endpoint docs. 

Do you think, it's worth adding a note here highlighting that?

2021-01-04 17:05 UTC, ethanroday commented
Ah, got it. In that case, LGTM! 🚀

2021-01-04 17:05 UTC, ethanroday approved these changes

2021-01-06 16:11 UTC, merged