Delete dashboard docs added
resource-watch/doc-api pull request #82
Opened 2019-12-02 13:38 UTC by pablopareja

2019-12-02 13:56 UTC, tiagojsag requested changes

2019-12-02 13:56 UTC, tiagojsag commented on source/includes/api/_dashboard.md
> +  - have role `MANAGER` or `USER` and be the dashboard's owner (through the `user-id` field of the dashboard)
https://github.com/resource-watch/resource-watch-manager/blob/35c71d09305c2d778ed49e07f04d46f324f9d937/spec/controllers/api/dashboards_update_spec.rb#L43

This was modified recently to mimic the behavior already found on other similar microservices - USERs cannot edit resources (even their own)

2019-12-02 13:56 UTC, tiagojsag commented on source/includes/api/_dashboard.md
> +  - have role `MANAGER` or `USER` and be the dashboard's owner (through the `user-id` field of the dashboard)
I think, technically, right now, any authenticates user can delete a dashboard. However, this is probably due to an oversight, and I think we should aim to change this so it mimics other resources (datasets, widgets, etc) where admins can delete any, managers their own, and users none

2019-12-02 13:58 UTC, tiagojsag commented
https://www.pivotaltracker.com/story/show/170050085

2019-12-03 11:30 UTC, pablopareja commented
@tiagojsag the changes you requested have been included in my last commit 😉

2019-12-09 07:06 UTC, merged